package com.cooksys.finals;

// Generated Aug 26, 2014 11:34:37 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * FilmActor generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class FilmActor implements java.io.Serializable {
	@XmlElement
	private FilmActorId id;
	@XmlElement
	private Actor actor;
	@XmlElement
	private Film film;
	@XmlElement
	private Date lastUpdate;

	public FilmActor() {
	}

	public FilmActor(FilmActorId id, Actor actor, Film film, Date lastUpdate) {
		this.id = id;
		this.actor = actor;
		this.film = film;
		this.lastUpdate = lastUpdate;
	}

	public FilmActorId getId() {
		return this.id;
	}

	public void setId(FilmActorId id) {
		this.id = id;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
